[server] Fix logging ldap error
If an `ldap.SERVER_DOWN` was thrown by the server for example when a wrong
connection url was given, the server tried to get the `message`
attribute of the exception an the following exception was thrown:
```
AttributeError: 'SERVER_DOWN' object has no attribute 'message'
```

The exception looked like this:
```
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 107,
  'info': 'Transport endpoint is not connected'}
```

This commit will remove the `log_ldap_error` function because it was
used only in one place and we just log the exception after converting
to str.