(FIPS) Added usedforsecurity=False to hashlib.md5(...)
Required on UBI-8 when host is FIPS compliant. It prevents:
> ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

It might not be portable. I use yum's python38 package on UBI-8.