[fix][cmd] Fix empty CodeChecker invocation
CodeChecker will throw the following exception when no subcommand is
given for the CodeChecker command:
```
Traceback (most recent call last):
  File "/cc_bin/CodeChecker.py", line 127, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

This patch will fix this problem and print the help message instead of
this exception.