[analyzer] Fix parse exception when file doesn't exist
If a source file referenced by a plist does not exist, the CodeChecker parse
was thrown the following exception:
```
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

This commit solves this problems and check whether the variable is None.