fix(report-converter): Support null column in eslint reports
ESLint reports may contain bugs with "column": null. Thus,
report-converter tool raises an exception:

TypeError: int() argument must be a string, a bytes-like object or a
number, not 'NoneType'

We set column number to 0 in such cases.